databases:
  - name: ISMNCubaDB
    plan: free
    databaseName: ismncuba
    user: ismncuba

services:
  - type: web
    plan: free
    name: ismn-cuba
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangoProject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 'CubaISMN'
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4