# Generated by Django 4.2.5 on 2024-02-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_editor_type_alter_rango_prefijo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefijoeditor',
            options={'verbose_name_plural': 'Prefijos_Editores'},
        ),
        migrations.AlterField(
            model_name='rango_prefijo',
            name='tipo',
            field=models.CharField(choices=[('P-Inferior', 'P-Inferior'), ('P-Menor', 'P-Menor'), ('P-Medio_Inferior', 'P-Medio_Inferior'), ('P-Superior', 'P-Superior'), ('P-Medio', 'P-Medio')], max_length=20, unique=True),
        ),
    ]
